version: '3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
      - ./attach:/usr/lumina/attach
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_DATABASE: luminadb
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mysqldb
      DB_USER: admin
      DB_PASSWORD: letmein
      DB_NAME: luminadb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 3000
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet
  nginx:
    image: nginx:alpine
    container_name: nginxcontainer
    volumes:
      - ../Front-end:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
