curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "titolo_di_servizio": "Croce", "titolo_opera": "Croce dipinta con <i>Cristo vivo</i>; nella cimasa, <i>Ascensione di Cristo</i>; nei terminali dei bracci orizzontali, <i>I quattro evangelisti in tetramorfo</i>; nelle tabelle laterali, di fianco al <i>Crocefisso (dall’alto) </i>: <i>San Giovanni e la Vergine dolenti</i> (a sinistra), <i>Due pie donne dolenti</i> (a destra); <i>Crocifissione di Disma</i> (a sinistra), <i>Crocifissione di Gesta (a destra) </i>; <i>Deposizione di Cristo nel sepolcro</i> (a sinistra), <i>Le Marie al sepolcro</i> (a destra)", "corpo_scheda": "Cristo crocifisso, qui nella formulazione iconografica del <i>triumphans</i>, è raffigurato vivo e con gli occhi bene aperti; la sua morte incipiente non dà segni manifesti di sofferenza fisica, se non nei rivoli di sangue, sottilissimi e calligrafici, che scaturiscono dai quattro chiodi confitti nelle mani e nei piedi; la caratterizzazione trionfante del soggetto è ulteriormente enfatizzata dal lungo perizoma, annodato sul davanti, impreziosito dal gallone dorato e dal colore purpureo delle vesti regali. La testa di Gesù è appena ruotata a destra, e i capelli, spartiti dalla marcata scriminatura centrale, ricadono in due ciocche ondulate che contornano ordinatamente il profilo delle spalle. Contravvenendo alla rigida assialità della figura condizionata dalla posa divaricata dei piedi, il busto è leggermente ruotato verso destra, come a voler suggerire un’impressione di scomposta naturalezza che si riverbera anche nel delicatissimo accavallamento della gamba sinistra sulla destra sottostante. Intorno a Gesù in croce si dispiega, in ordinata simmetria, un apparato di figure ed episodi che contestualizzano in senso narrativo il momento della Passione, esaltandone al contempo il messaggio trionfale e soteriologico: esso è particolarmente congeniale alla simbologia dell’altare eucaristico (Sinding Larsen 1978, pp. 193-195; Bacci 1994, p. 90), nelle cui immediate prossimità dovevano trovarsi questa ed altre croci monumentali, forse issate <i>in trabe</i> tra l’<i>ecclesia laicorum</i> e il presbiterio (speciatim Peroni 2012; Massaccesi 2019, con ulteriore bibliografia). 
Nella cimasa, poco al di sopra della tabella dell’INRI, è la <i>Maiestas Domini</i>, con ai lati due angeli riverenti; intorno alle estremità fiorite dei bracci orizzontali della Croce trovano posto gli Evangelisti nei quattro simboli del Tetramorfo: a sinistra, il Figlio dell’Uomo di San Matteo e il leone di San Marco; a destra, l’aquila di San Giovanni e il bue di San Luca. Il teatro dei dolenti – con <i>Giovanni Evangelista e la Vergine</i>, legati dal gesto della <i>coniunctio dextrarum</i> (Bagnarol 2012), e le <i>Due Marie</i> – occupa il primo registro del tabellone centrale, da un lato e dall’altro del busto di Cristo; immediatamente al di sotto si trovano descritte, in scala inferiore, la <i>Crocifissione del buon ladrone</i> (a destra) e la <i>Crocifissione del cattivo ladrone</i> (a sinistra); i due, legati alla rispettiva croce, stanno per essere fatalmente colpiti da altrettanti sgherri che, con pose in contrappunto (uno si volge verso il suo ladrone, il secondo dà all’altro le spalle), trattengono la violenza del colpo incipiente in una sorta di sinuoso passo di danza. In basso a sinistra trova posto la <i>Deposizione di Cristo nel sepolcro</i>, ambientata entro un baldacchino cupolato, allusivo all’edificio del Santo Sepolcro di Gerusalemme (Bacci 1994, p. 92), e officiata da tre personaggi. Al centro della scena è il ricco e anziano Giuseppe d’Arimatea; questi regge incongruamente tra le mani la pisside degli unguenti, che – stando al racconto evangelico – sarebbe invece più appropriata a Nicodemo, posto ai piedi del sarcofago strigilato all’antica dove aiuta a deporre il corpo morto di Cristo rinvolto nel sudario, che una terza figura – da identificare forse con l’efebico San Giovanni Evangelista – sostiene dal capo, dall’altra parte del sepolcro. Nel riquadro complanare, a destra del Crocifisso, è descritto l’episodio delle <i>Marie al sepolcro</i>, a compendio del racconto della Resurrezione. Vi è ripetuto il medesimo baldacchino cupolato della scena precedente, che qui, in un’ulteriore rappresentazione sintetica ma più completa del Santo Sepolcro (Bacci 1994, p. 92), insiste su un’edicola scavata nella roccia che pare far corpo unico con il sarcofago strigilato in cui Cristo veniva poc’anzi deposto. Conformemente al Vangelo di Matteo e alla tradizione figurativa orientale da questo derivata (Bacci 1994, p. 93), sono presenti nella scena solo due delle più canoniche tre donne testimoni della resurrezione di Gesù; ad annunciare loro l’evento è l’angelo che, munito di scettro, indica alle Marie il sepolcro ormai vuoto.   
Il dipinto fu interessato da un primo restauro di Nicola Carusi tra il 1963 e il 1966 (457/09, ex LU552), che consistette nel consolidamento dei bracci orizzontali, a quel tempo gravemente sconnessi; in anni più recenti (2000-2006) è stato oggetto di un secondo intervento, in occasione del quale sono state effettuate analisi tecniche – stratigrafiche e chimiche – sulla composizione della superficie pittorica (239/09). Nel complesso, l’opera mantiene un grado di leggibilità discreto, al netto della crettatura diffusa della lamina dorata e del depauperamento della materia cromatica, più accentuato nelle minute figurazioni di contorno; si segnalano, inoltre, tracce di pigmentazione rossastra, ora scurita, nel tergo e lungo gli spessori della Croce, che erano probabilmente pertinenti all’uniforme colorazione originaria del retro.
L’assemblaggio del supporto, composto da tavole in legno di castagno a venatura verticale (Bellucci 2001, p. 43), è avvenuto secondo modalità riscontrabili negli esemplari tipologicamente affini alla Croce qui esaminata, quali la Croce di <i>Guillelmus</i> del Duomo di Sarzana e la Croce di San Michele in Foro a Lucca (Castelli 2012). I quattro bracci risultano dall’incastro a mezzo legno di più assi lignee; la connessione delle parti era, in origine, ulteriormente assicurata da una traversa lignea orizzontale, poi sostituita da un elemento metallico nel corso di un recente restauro (D’Aniello 2012, p. 184). Ai bracci trasversali sono inchiodate lateralmente due tabelle centralmente convesse; una terza, di forma analoga, sovrasta il <i>ritto</i> della Croce. Ulteriore elemento aggiunto è il disco del nimbo di Cristo, inchiodato frontalmente al supporto e dunque aggettante. L’ampio tavolato centrale, composto dalla connessione di più assi, è stato sagomato lungo i bordi laterali inferiori secondo un profilo curvilineo e convesso, così da restituire quella forma ‘a calice’ che è tipica di un ristretto gruppo di croci di area lucchese (Black 1941; Garrison 1949) e nella quale si può forse leggere una suggestiva allusione  all’allestimento ottoniano del culto del Preziosissimo Sangue, contenuto in un calice posto sotto il piede destro della sacra effigie del Volto Santo, nella cattedrale di San Martino (Black 1941; Silva 1980, pp. 99-100; Monciatti 2014, p. 273). Tale formato, peculiarissimo, è comune alle Croci di San Michele in Foro, del Duomo di Sarzana, alla Croce ‘della Zecca’, nonché a quella della chiesa parrocchiale di Cevoli, esemplata sul più autorevole modello della Croce del Foro; la “chalice-shape base” non è presente, invece, nella Croce di Santa Giulia che, nella sagoma più regolare, si approssima piuttosto alle croci dipinte pisane realizzate tra il secondo e il terzo quarto del secolo. 
La distesa uniforme della lamina d’oro del fondo, applicata direttamente sulla tela senza l’intermediazione del bolo (com’è tipico della pittura del XII secolo), è resa appena più vibrante dal ricorso insistito a una sottile decorazione incisa a orbicoli, impiegata per contornare il perimetro dei campi figurati, per decorare i nimbi delle figure sacre, per rifinire le coperte dei libri del Tetramorfo e il prezioso gallone del perizoma di Gesù. Nelle parti figurate, la differenziazione tecnica dei materiali, perseguita attraverso il risparmio selettivo della lamina dorata, è funzionale all’enfatizzazione di alcuni elementi iconografici di particolare pregnanza simbolica: sono, infatti, risparmiati sull’oro le coperte dei Vangeli del Tetramorfo, il gallone del perizoma di Cristo e, infine, le teste dei quattro chiodi confitti nei piedi e nelle mani del Crocifisso, dorate anche nella Croce della cattedrale di Sarzana e in quella di Santa Giulia a Lucca, ora nel Duomo cittadino. 
In mancanza di riferimenti esterni capaci di orientare puntualmente la datazione e l’analisi stilistica dell’opera, i problematici tentativi di inquadramento critico della Croce dei Servi si sono avvalsi, già nelle prime segnalazioni, del confronto dell’opera con i tre esemplari lucchesi congeneri (San Michele in Foro, Santa Giulia, Zecca). Le vicende critiche di questi dipinti procedono perciò quasi sempre di pari passo, intrecciandosi, inoltre, con quelle della Croce di <i>Guillelmus</i> a Sarzana che, unica precisamente datata, ha guidato talvolta il riordino cronologico del gruppo di opere; già considerato la matrice delle croci lucchesi  in virtù della sua data apparentemente alta (van Marle 1923), il dipinto sarzanese è, più verosimilmente, una risposta a caldo alle prime e importanti recensioni lucchesi della tipologia, da identificare con la Croce qui esaminata e con la gemella in scala maggiore di San Michele in Foro. È quest’ultima, in particolare, ad aver attirato nel cono di luce della sua fortuna critica le vicende della Croce dei Servi. Nonostante le perplessità di alcuni (speciatim Marques 1987, Monciatti 2012, Monciatti 2014), i due esemplari sono infatti innegabilmente opera di uno stesso pittore, battezzato da Richard Offner (1930) come Maestro della Croce di San Michele in Foro, autore, a date più avanzate, pure della Madonna col Bambino del Museo Horne di Firenze (Boskovits 2021, p. ***; contra Bianchi 2020), iconograficamente e tipologicamente vicina alla superba <i>Madonna col Bambino</i>, già nella chiesa di Santa Chiara a Pisa (ora ivi, ma  Museo Nazionale di San Matteo), che potrebbe essere una primizia, qualitativamente eccelsa, del medesimo pittore.  
Dopo un iniziale assestamento alla fine del XII secolo, la datazione della Croce dei Servi è stata più congruamente anticipata alla prima metà del secolo, soprattutto alla luce di due importanti riferimenti cronologici recuperati per la gemella di San Michele in Foro. Questa, infatti, esisteva già nel 1170 ed era stata probabilmente confezionata in anni immediatamente precedenti al 1143, data incisa sul pilastro destro dell’area presbiteriale della chiesa di San Michele a celebrare simbolicamente la conclusione del rifacimento e, forse, del riarredo della zona absidale (Tigler 2006). Come ben argomentato da Alessio Monciatti (2012, 2014) sulla falsariga di intriganti attestazioni documentarie risalenti alla fine dell’XI secolo, è probabile che nel Duomo lucchese esistesse una più antica Croce monumentale in oreficeria – poi perduta – di cui quella del Foro sarebbe un’intelligente traduzione in pittura: in quest’ultimo caso, infatti, il ricorso unico al rilievo del corpo di Cristo (Castelli 2012, p. 77, per note tecniche) potrebbe rappresentare un lampante tentativo di simulazione dello sbalzo della lamina metallica dell’archetipo. Se è lecito intendere l’ibridazione tecnica – di pittura e scultura –, attestata nella Croce di San Michele, come il segno di una transizione <i>in fieri</i>, dalle più tradizionali Croci monumentali in metallo ai più moderni esemplari dipinti, all’opera del Foro dev’essere allora riconosciuto il ruolo di incunabolo della tipologia lucchese e, dunque, una datazione più alta rispetto alla Croce di Villa Guinigi, come confermano anche i dati di stile e alcune indiziarie circostanze di contesto. La simmetria della composizione iconografica complessiva, bilanciata sui due lati del corpo di Cristo, è  più controllata nella Croce dei Servi che in quella del Foro: si veda, in particolare, come nella prima il pittore riesca a governare razionalmente la difficile svasatura della sagoma a calice inserendovi due mezze colonne dipinte per pareggiare i riquadri figurati soprastanti, che sono invece disallineati nell’altra croce, dove perciò tradiscono un certo impaccio nel controllo di quel peculiarissimo – e forse ancora inedito – formato. Nell’esemplare di Villa Guinigi si osserva, inoltre, un’attenzione più perspicua e moderna agli effetti di aderenza dei panneggi sulle rotondità anatomiche, del tutto assenti nella croce di San Michele ma qui restituiti con liquide velature di colore sovrapposte; questi nuovi interessi potrebbero essere germinati dall’esperienza dell’anonimo pittore degli esiti neo-antichizzanti e velleitariamente naturalistici tentati da <i>Guillelmus</i> a Sarzana e dal miniatore lucchese responsabile delle splendide illustrazioni del Passionario P† (Lucca, Biblioteca Capitolare Feliniana), datate agli anni quaranta del secolo. 
L’ipotesi della posteriorità della Croce dei Servi rispetto a quella di San Michele in Foro, dedotta dalle argomentazioni stilistiche, può inoltre essere meglio circostanziata da alcune considerazioni sulla provenienza e sulla possibile committenza dell’opera. Si ritiene, infatti, che la croce fosse giunta nella chiesa di Santa Maria dei Servi dall’antica chiesa di San Michele degli Avvocati (Belli Barsali 1970, p. 170; Caleca 1982, pp. 76-79: 77; D’Aniello 2017), inglobata alla metà del Duecento dalla neonata fondazione servita. Poco si sa dell’assetto dell’edificio più antico, se non che sorgesse, tra il Duomo e il Foro, nella corte della famiglia degli Avvocati, appartenenti al ceto dei giudici ed eminenti rappresentanti dell’élite diocesana lucchese, con «una complessa funzione di raccordo tra l’ordinamento pubblico dell’Impero (…)» (Savigni 1996, p. 55). Il capostipite Filiperto o Flaiperto, attestato sino al 1075, fu intermediario di spicco nei contrasti tra Matilde di Canossa ed Enrico IV, ma il ruolo politico della famiglia andò a rafforzarsi ulteriormente nel corso del XII secolo, come esito ultimo di un’«emergente autocoscienza cittadina» (Savigni 1996, p. 58), al punto che Tancredi arrivò ad assumere nel 1152 la carica di console. Il contesto di crescente legittimazione politica degli Avvocati profilatosi verso la metà del secolo sembra uno scenario propizio alla realizzazione di uno dei primi esemplari delle <i>cruces</i> dipinte monumentali della tradizione occidentale, che, nella fattispecie, pare logico far derivare da quello, ben più grande e autorevole, già presente nella chiesa del Foro e che, a sua volta, poteva essere copia di un più illustre archetipo perduto presente in Duomo. La diffusione locale della tipologia parrebbe, infatti, essere avvenuta in forma quasi stemmatica e fu forse determinata nelle principali fondazioni religiose lucchesi da quei fenomeni di emulazione reciproca dei rispettivi apparati liturgici e figurativi frequentissimi tra i secoli XII e XIII (si veda, in particolare, la vivace competizione tra i cantieri di San Martino e di San Michele in Foro: Tigler 2006). A questo paradigma non si sottrasse la chiesa degli Avvocati, che dovette guardare in maniera privilegiata alla vicina chiesa del Foro, alla quale la legavano sia la comune intitolazione all’arcangelo, sia la destinazione a specifiche funzioni politiche: se in una la famiglia patrona esercitava le proprie attività giurisdizionali in senso filo-episcopale, nell’altra aveva sede la curia giudiziaria dei <i>consules de placito</i>, espressione della <i>civitas lucchese</i> (Savigni 1996, p. 63). 
", "iscrizioni": "nel tabellone apicale I(e)S[us n]AZARENU(s) // REX IUDEORUM", "descrizione_sintetica": "<i>Cristo crocefisso</i>, presentato secondo il tipo iconografico del <i>triumphans</i>, è vivo e vittorioso sulla morte. Intorno al suo corpo, si dispiega un apparato di figure ed episodi narrativi che celebrano ed esaltano il significato soteriologico della Passione: in alto, nella cimasa, la <i>Maiestas Domini</i>; i quattro <i>Evangelisti</i> nelle sembianze animali del Tetramorfo, disposti a coppie al termine dei bracci della croce; ai fianchi del Cristo, <i>San Giovanni Evangelista e la Madonna dolenti</i>, da una parte, due <i>Marie</i>, dall’altra; nei registri inferiori, la <i>Crocefissione del cattivo ladrone</i> e la <i>Deposizione di Cristo nel sepolcro</i>, a sinistra; la <i>Crocefissione del buon ladrone</i> e le <i>Marie al Sepolcro</i>, a destra.
L’opera qui discussa rappresenta un importante testimone della discreta fortuna che la tipologia della croce dipinta ebbe a Lucca nel corso del XII secolo, a effetto di un fiorente culto cittadino, probabilmente germinato dal Volto Santo (Monciatti 2012); la grande devozione cristologica lucchese incise anche sul rarissimo formato del manufatto, che è inferiormente svasato per riecheggiare la sagoma del calice eucaristico (Black 1941). La rispondenza a peculiari caratteristiche di formato, di iconografia e – in parte – di stile, lega indissolubilmente questo esemplare a quattro Croci congeneri, similmente databili al XII secolo. Il gruppo configura l’esistenza di un preciso canone tipologico locale della croce dipinta: una sorta di “Lucchese type” al quale ciascun testimone si adegua con grado variabile di fedeltà (Sandberg Vavalà 1929; Gaeta 2013, pp. 28-31). Dei quattro esemplari citati, tre sono saldamente radicati nel territorio urbano lucchese: la monumentale Croce di San Michele in Foro, la Croce già nella chiesa di Santa Giulia e ora nel duomo di Lucca, la Croce detta ‘della Zecca’ dal Monastero omonimo, ultimo luogo noto di provenienza dell’opera prima che questa approdasse al Museo di Villa Guinigi (***). Alla serie va aggiunta la Croce di <i>Guillelmus</i>, datata 1138, probabilmente realizzata in origine per la chiesa di Sant’Andrea a Sarzana (ora <i>ivi</i>, ma in Duomo), cittadina ligure allora pertinente alla diocesi di Luni e per questo investita dal raggio dell’influenza lucchese.
", "storia_espositiva": "Giunta nel 1899 nelle collezioni pubbliche lucchesi dalla chiesa duecentesca di Santa Maria dei Servi, dov’era conservata prima nel coro, poi nella sacrestia (Ridolfi 1877; Id.1899), la Croce fu inizialmente compresa nell’allestimento della Pinacoteca di Palazzo Ducale (Campetti 1912) e transitò successivamente nelle sale del Museo civico di Villa Guinigi, inaugurato nel 1924.", "classificazione": "Dipinto"}' \  http://0.0.0.0:3000/schede
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "formula_precedente": "", "formula_successiva": "", "categoria": "Opera attribuita", "nome": "Maestro della Croce di San Michele in Foro"}' \  http://0.0.0.0:3000/autori

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": 5, "id_autore": 1}' \  http://0.0.0.0:3000/tds_schede_autori
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "ambito_storico": "", "etichetta_data": "1145-1150 ca.", "giorno_data_da": "01", "mese_data_da":"01", "anno_data_da": "1145", "giorno_data_a": "31", "mese_data_a":"12", "anno_data_a": "1150"}' \  http://0.0.0.0:3000/cronologie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": 5, "id_cronologia": 1}' \  http://0.0.0.0:3000/tds_schede_cronologie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "nome_materiale": "legno di castagno, lamina dorata", "descrizione": ""}' \  http://0.0.0.0:3000/materiali
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": 5, "id_materiale": 1}' \  http://0.0.0.0:3000/tds_schede_materiali
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "nome_tecnica": "pittura a tempera, oro a guazzo", "descrizione": ""}' \  http://0.0.0.0:3000/tecniche
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": 5, "id_tecnica": 1}' \  http://0.0.0.0:3000/tds_schede_tecniche
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "ubicazione": "Lucca, Museo Nazionale di Villa Guinigi", "descrizione": ""}' \  http://0.0.0.0:3000/ubicazioni
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_ubicazione": "1"}' \  http://0.0.0.0:3000/tds_schede_ubicazioni
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "numero_inventario": "331", "nome_inventario": "", "descrizione": ""}' \  http://0.0.0.0:3000/inventari
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_inventario": "1"}' \  http://0.0.0.0:3000/tds_schede_inventari
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "provenienza": "", "descrizione": "", "note": "Lucca, sacrestia della chiesa di Santa Maria dei Servi, 1899"}' \  http://0.0.0.0:3000/provenienze
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_provenienza": "1"}' \  http://0.0.0.0:3000/tds_schede_provenienze

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "curatore": "", "titolo_mostra": "<i>Esposizione di Arte e Industria antica</i>", "giorno_data_da": "", "mese_data_da":"", "anno_data_da": "1893", "giorno_data_a": "", "mese_data_a":"", "anno_data_a": "1893", "luogo_mostra": "Lucca", "descrizione": "Palazzo della Provincia"}' \  http://0.0.0.0:3000/mostre
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_mostra": "1"}' \  http://0.0.0.0:3000/tds_schede_mostre

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "2", "curatore": "", "titolo_mostra": "<i>Mostra giottesca</i>", "giorno_data_da": "", "mese_data_da":"04", "anno_data_da": "1937", "giorno_data_a": "", "mese_data_a":"04", "anno_data_a": "1937", "luogo_mostra": "Firenze", "descrizione": "Galleria degli Uffizi"}' \  http://0.0.0.0:3000/mostre
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_mostra": ""}' \  http://0.0.0.0:3000/tds_schede_mostre

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "3", "curatore": "", "titolo_mostra": "<i>Trésors d’Art</i>,", "giorno_data_da": "", "mese_data_da":"05", "anno_data_da": "1952", "giorno_data_a": "", "mese_data_a":"07", "anno_data_a": "1952", "luogo_mostra": "Parigi", "descrizione": "Musée du Petit Palais"}' \  http://0.0.0.0:3000/mostre
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_mostra": ""}' \  http://0.0.0.0:3000/tds_schede_mostre


curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "riferimento_bibliografico": "T. Bini, <i>Notizie della chiesa e del crocifisso di Santa Giulia a Lucca</i>, Lucca 1858, p. 10."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "2", "riferimento_bibliografico": "J.A. Crowe, G.B. Cavalcaselle, <i>A New History of Painting in Italy from the Second to the Sixteenth century</i>, 3 voll., London 1864-1866, I, 1864, p. 158."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "3", "riferimento_bibliografico": "E. Ridolfi, <i>Guida di Lucca</i>, Lucca 1877, p. 86."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "4", "riferimento_bibliografico": "E. Ridolfi, <i>Guida di Lucca</i>, Lucca 1899, p. 94."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "5", "riferimento_bibliografico": "P. Campetti, <i>Guida di Lucca</i>, Lucca 1912, p. 93."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "6", "riferimento_bibliografico": "O. Sirén, <i>Toskanische Maler im XIII. Jahrundert</i>, Berlin 1922, p. 56."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "7", "riferimento_bibliografico": "R. van Marle, <i>The Development of the Italian Schools of Painting</i>, 19 voll., The Hague 1923-1938, I, 1923, p. 214."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "8", "riferimento_bibliografico": "G. Rosadi, <i>Lucca nel sogno del suo silenzio. Discorso dell’On. Giovanni Rosadi alla inaugurazione della Villa Guinigi ripristinata il XIII settembre MCMXXIV</i>, Lucca, 12 ottobre 1924."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "9", "riferimento_bibliografico": "G.M. Richter, <i>The Crucifix of Guillelmus at Sarzana</i>, in “The Burlington Magazine for Connoisseurs”, LI, 1927, pp. 162-177: 168, 174."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "10", "riferimento_bibliografico": "P. Toesca, <i>Il Medioevo</i>, Torino 1927, p. 934."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "11", "riferimento_bibliografico": "E. Sandberg Vavalà, <i>Quattro croci romaniche a Sarzana e a Lucca</i>, in “Dedalo”, IX, 1928, pp. 65-96."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "12", "riferimento_bibliografico": "E. Sandberg Vavalà, <i>La croce dipinta italiana e l’iconografia della passione</i>, Verona 1929, p. 519."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "13", "riferimento_bibliografico": "R. Offner, <i>The Mostra del Tesoro di Firenze Sacra</i>, I, in “The Burlington Magazine for Connoisseurs”, LXIII, 1933, pp. 72-84: 76."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "14", "riferimento_bibliografico": "<i>Mostra giottesca. Onoranze a Giotto nel VI centenario della morte</i>, catalogo della mostra (Firenze, Palazzo degli Uffizi, aprile - ottobre 1937), Bergamo 1937, p. 13 cat. 1."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "15", "riferimento_bibliografico": "E.B. Garrison, <i>Italian Romanesque Panel Painting. An Illustrated Index</i>, Firenze 1949, pp. 21, 28, 195."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "16", "riferimento_bibliografico": "<i>Trésors d’Art du Moyen Age en Italie</i>, catalogo della mostra (Paris, Musée du Petit Palais, maggio - luglio 1952), Paris 1952, cat. 157."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "17", "riferimento_bibliografico": "F. Bologna, <i>La pittura italiana delle origini</i>, Roma 1962, p. 53."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "18", "riferimento_bibliografico": "L. Bertolini Campetti, in <i>Museo di Villa Guinigi, Lucca: la villa e le collezioni</i>, a cura di L. Bertolini Campetti, S. Meloni Trkulja, Lucca 1968, pp. 136-137."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "19", "riferimento_bibliografico": "I. Belli Barsali, <i>Guida di Lucca</i>, Lucca 1970, pp. 131, 170, fig. 69."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "20", "riferimento_bibliografico": "F.A. Dal Pino, <i>I frati Servi di S. Maria dalle origini all’approvazione (1233 ca. - 1304) </i>, 3 voll., Louvain 1972, I, p. 180."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "21", "riferimento_bibliografico": "S. Sinding-Larsen, <i>Some Observations on Liturgical Imagery of the Twelfth Century</i>, in “Acta ad archaeologiam et atrium historiam pertinentia”, VIII, 1978, pp. 193-212: 193-195."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "22", "riferimento_bibliografico": "A. Derbes, <i>Byzantine Art and the Dugento: Iconographic Sources of the Passion Scenes in Italian Painted Crosses</i>, Charlottesville, University of Virginia 1980, pp. 7, 275-278, 308-310."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "23", "riferimento_bibliografico": "L.C. Marques, <i>La peinture du Duecento en Italie centrale</i>, Paris 1987, pp. 71, 241-242 nota 117."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "24", "riferimento_bibliografico": "M. Boskovits, <i>A Critical and Historical Corpus of Florentine Painting. I,1. The Origins of Florentine Painting, 1100-1270</i>, Firenze 1993, pp. 30-31."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "25", "riferimento_bibliografico": "A. Caleca, <i>La pittura medievale in Toscana</i>, in <i>La pittura in Italia. L’Altomedioevo</i>, a cura di C. Bertelli, Milano 1994, pp. 163-180: 169."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "26", "riferimento_bibliografico": "M. Bacci, <i>La croce di Santa Giulia</i>, in “Rivista di archeologia, storia, costume”, XXVI, 1998, pp. 87-102: 89."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "27", "riferimento_bibliografico": "S.B. Choate, <i>Devotion and Narrative within the Tradition of the ‘croce dipinta’</i>, Ph.D. dissertation, Florida State University, Ann Arbor (MI) 2007, pp. 98 nota 10, 167."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "28", "riferimento_bibliografico": "M. Ciatti, <i>The Typology, Meaning, and Use of Some Panel Paintings from the Duecento and Trecento</i>, in “Studies in the History of Art”, LXI, 2002, pp. 15-29: 23-28."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "29", "riferimento_bibliografico": "K. Schüppel, <i>Pictae et sculptae: Tafelkreuze und pastiche Kruzifixe im lokalen liturgischen Kontext, die Städte Lucca, Arezzo und Neapel</i>, in “Römisches Jahrbuch der Bibliotheca Hertziana”, XXXVIII, 2007-2008, pp. 77-112: 88-90."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "30", "riferimento_bibliografico": "A. d’Aniello, <i>Materia e colore, le croci dipinte lucchesi dopo i recenti restauri, in <i>La pittura su tavola del secolo XII. Riconsiderazioni e nuove acquisizioni a seguito del restauro della Croce di Rosano</i>, a cura di C. Frosinini, A. Monciatti e G. Wolf, Firenze 2012, pp. 183-192."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "31", "riferimento_bibliografico": "A. Monciatti, <i>Le Croci dipinte in area lucchese: modelli e tipi figurali</i>, in <i>La pittura su tavola del secolo XII. Riconsiderazioni e nuove acquisizioni a seguito del restauro della Croce di Rosano</i>, a cura di C. Frosinini, A. Monciatti e G. Wolf, Firenze 2012, pp. 163-173"}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "32", "riferimento_bibliografico": "S. Bagnarol, <i>Dall’intercessione alla compassione: San Giovanni e la Vergine, la “Coniunctio dextrarum” e l’iconografia della crocefissione nel passaggio tra secolo XII e XIII</i>, in <i>La pittura su tavola del secolo XII. Riconsiderazioni e nuove acquisizioni a seguito del restauro della Croce di Rosano</i>, a cura di C. Frosinini, A. Monciatti e G. Wolf, Firenze 2012, pp. 215-222: 216."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "33", "riferimento_bibliografico": "M. Gaeta, <i>Giotto und die “croci dipinte” des Trecento: Studien zu Typus, Genese und Rezeption, mit einem Katalog der monumentalen Tafelkreuze des Trecento (ca. 1290-ca. 1400) </i>, Münster 2013, pp. 29, 32."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "34", "riferimento_bibliografico": "A.M. Calderoni Masetti, <i>Miniatura a Lucca fra XII e XIII secolo: “prolegomena” a un’esposizione<i>, in <i>Scoperta armonia: arte medievale a Lucca</i>, a cura di C. Bozzoli, M.T. Filieri, V. Ascani, Lucca 2014, pp. 155-176. "}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "35", "riferimento_bibliografico": "A. d’Aniello, <i>La croce dipinta in area lucchese: riflessioni su diffusione, storia materiale e iconografia dal XII secolo a Berlinghiero</i>, in <i>Inkarnat und Signifikanz: das menschliche Abbild in der Tafelmalerei von 200 bis 1250 im Mittelmeerraum</i>, a cura di Y. Schmuhl, E.P. Wipfler, München 2017, pp. 380-391."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "36", "riferimento_bibliografico": "F. Bianchi, <i>Appunti su due Madonne col Bambino di area pisano-lucchese del XII secolo ed una proposta iconografica riguardante un prototipo di cardellino</i>, in “Arte cristiana”, CVIII, 2020, 916, pp. 38-47. "}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie

url --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "riferimento_bibliografico": "M. Boskovits, S. Chiodo, <i>A Critical and Historical Corpus of Florentine Painting</i>. Suppl. <i>Mediaeval Panel Painting in Tuscany 12th to 13th century</i> 2021, pp. 48-49 cat. 4."}' \  http://0.0.0.0:3000/bibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_bibliografie


curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "riferimento_bibliografico": "R. Savigni, <i>Episcopato e società cittadina a Lucca da Anselmo II (+1086) a Roberto (+1225) </i>, Lucca 1996." \  http://0.0.0.0:3000/altreBibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_altreBibliografie

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "2", "riferimento_bibliografico": "G. Tigler, <i>Toscana romanica</i>, Milano 2006." \  http://0.0.0.0:3000/altreBibliografie
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_bibliografia": "1"}' \  http://0.0.0.0:3000/tds_schede_altreBibliografie



curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "001","path": "../api/attach/pictures/1/1. Croce dei Servi, intero, fronte.jpg","didascalia": "Croce dei Servi, intero, fronte"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "001"}' \  http://0.0.0.0:3000/tds_schede_immagini

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "002","path": "../api/attach/pictures/1/2. Braccio destro, particolare.jpg","didascalia": "Braccio destro, particolare"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "002"}' \  http://0.0.0.0:3000/tds_schede_immagini

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "003","path": "../api/attach/pictures/1/3. Cristo trionfante, particolare.jpg","didascalia": "Cristo trionfante, particolare.jpg"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "003"}' \  http://0.0.0.0:3000/tds_schede_immagini

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "004","path": "../api/attach/pictures/1/4. Crocefissione del buon ladrone, Le Marie al sepolcro di Cristo.jpg","didascalia": "Crocefissione del buon ladrone, Le Marie al sepolcro di Cristo"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "004"}' \  http://0.0.0.0:3000/tds_schede_immagini

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "005","path": "../api/attach/pictures/1/5. Crocefissione del cattivo ladrone, Deposizione di Cristo nel sepolcro.jpg","didascalia": "Crocefissione del cattivo ladrone, Deposizione di Cristo nel sepolcro"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "005"}' \  http://0.0.0.0:3000/tds_schede_immagini

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "006","path": "../api/attach/pictures/1/6. I dolenti, Crocefissione del cattivo e del buon ladrone.jpg","didascalia": "I dolenti, Crocefissione del cattivo e del buon ladrone"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "006"}' \  http://0.0.0.0:3000/tds_schede_immagini

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "007","path": "../api/attach/pictures/1/7. Le Marie dolenti, Crocefissione del buon ladrone.jpg","didascalia": "Le Marie dolenti, Crocefissione del buon ladrone"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "007"}' \  http://0.0.0.0:3000/tds_schede_immagini

curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "008","path": "../api/attach/pictures/1/8. San Giovanni e la Vergine dolenti, Crocefissione del cattivo ladrone.jpg","didascalia": "San Giovanni e la Vergine dolenti, Crocefissione del cattivo ladrone"}' \  http://0.0.0.0:3000/immagini
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5","id_immagine": "008"}' \  http://0.0.0.0:3000/tds_schede_immagini


curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "riferimento_bibliografico": "Croci (Bologna), 2769-2779; Alinari, Firenze, 18172, 43370-43372; Anderson, Firenze, 40768; Artini, Firenze, 441, 313389-313394; Soprintendenza, Firenze, 7902-7905, 12601, 26701; Mario Sansoni © Frick Reference Art Library, New York, 6583-6584; Soprintendenza, Pisa, 60361; Soprintendenza, Lucca e Massa Carrara © Musei Nazionali, 21268-2191; Musei Nazionali, 22453-22464; Giovanni Martellucci, Università degli studi di Firenze © Musei Nazionali di Lucca, ***-***"}' \  http://0.0.0.0:3000/documentazioniFotografiche
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": "5", "id_documentazioneFotografica": "1"}' \  http://0.0.0.0:3000/tds_schede_documentazioniFotografiche


curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "intero_parziale": "parziale", "titolo_gruppo_misure": "intero", "id_tds": "1", note:""}' \  http://0.0.0.0:3000/tds_schede_gruppo_misure
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "1", "direzione": "altezza", "tipo": "massima", "valore": 227, "unita_di_misura": "cm", "id_gruppo_misure": "1"}' \  http://0.0.0.0:3000/misure
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id": "2", "direzione": "larghezza", "tipo": "massima", "valore": 179, "unita_di_misura": "cm", "id_gruppo_misure": "1"}' \  http://0.0.0.0:3000/misure



curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": 5, "id_gruppo_misure": 1}' \  http://0.0.0.0:3000/tds_schede_misure
curl --header "Content-Type: application/json" \  --request POST \  --data '{"id_scheda": 5, "id_gruppo_misure": 2}' \  http://0.0.0.0:3000/tds_schede_misure

